package shortestpath.requirement;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import lombok.extern.slf4j.Slf4j;
import shortestpath.Util;
import shortestpath.transport.TransportType;

/**
 * Per-item teleport restriction support: the family map the config panel's
 * restriction checklist groups by, plus the CSV contract shared by the hidden
 * {@code blockedTeleportItems} config key.
 *
 * <p>
 * The '#'-category headers in {@code teleportation_items.tsv} are comments that
 * {@link shortestpath.transport.parser.TsvParser} skips at runtime, so the
 * grouping is materialized as its own bundled resource
 * ({@code /transports/teleport_restrictions.tsv}) generated by
 * {@code scripts/generate_teleport_restrictions.py}. Every numeric item id in
 * the source TSV belongs to exactly one family; {@code teleportation_boxes.tsv}
 * carries no {@code Items} column and is out of scope for id-keyed blocking.
 * </p>
 *
 * <p>
 * CSV contract: a comma-separated list where a bare {@code id} record blocks
 * the item and an {@code id:N} record sets a per-item threshold override of N
 * tiles. Unknown or malformed entries are skipped with a warning — user- or
 * profile-authored CSV must never break {@code refresh()} or panel
 * construction. Empty string means "no restrictions" (the default).
 * </p>
 */
@Slf4j
public final class TeleportRestriction
{
	private static final String FAMILY_RESOURCE = "/transports/teleport_restrictions.tsv";

	private TeleportRestriction()
	{
	}

	/**
	 * The transport types whose item requirements are player-restrictable:
	 * per-item blocks and threshold overrides only consult these. Other types
	 * (boats, agility shortcuts, POH teleports, …) keep item requirements as
	 * pure inventory constraints.
	 */
	public static boolean isItemTeleportType(TransportType type)
	{
		return TransportType.TELEPORTATION_ITEM.equals(type)
			|| TransportType.SEASONAL_TRANSPORTS.equals(type)
			|| TransportType.QUETZAL_WHISTLE.equals(type);
	}

	/**
	 * A named group of teleportation item ids. {@code displayItemId} is the
	 * family's representative item (used for the checklist row icon);
	 * {@code memberItemIds} is the sorted set of raw item ids the family
	 * covers; {@code memberLabels} maps each member id to the display label
	 * harvested from the source TSV's {@code Display info} prefixes — the
	 * variant-match surface for checklist search.
	 */
	public static final class Family
	{
		private final String name;
		private final int displayItemId;
		private final Set<Integer> memberItemIds;
		private final Map<Integer, String> memberLabels;

		public Family(String name, int displayItemId, Set<Integer> memberItemIds,
			Map<Integer, String> memberLabels)
		{
			this.name = name;
			this.displayItemId = displayItemId;
			this.memberItemIds = memberItemIds;
			this.memberLabels = memberLabels;
		}

		public String name()
		{
			return name;
		}

		public int displayItemId()
		{
			return displayItemId;
		}

		public Set<Integer> memberItemIds()
		{
			return memberItemIds;
		}

		public Map<Integer, String> memberLabels()
		{
			return memberLabels;
		}
	}

	/**
	 * Loads the bundled family map. Malformed rows are skipped with a warning
	 * (the checklist degrades to fewer rows rather than crashing); an absent or
	 * malformed {@code memberLabels} column degrades to an empty map for that
	 * family.
	 */
	public static List<Family> loadFamilies()
	{
		final String contents;
		try
		{
			contents = new String(
				Util.readAllBytes(
					Objects.requireNonNull(TeleportRestriction.class.getResourceAsStream(FAMILY_RESOURCE))),
				StandardCharsets.UTF_8);
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}

		List<Family> families = new ArrayList<>();
		for (String line : contents.split("\n"))
		{
			if (line.startsWith("#") || line.isBlank())
			{
				continue;
			}

			String[] fields = line.split("\t", -1);
			if (fields.length < 3)
			{
				log.warn("Skipping malformed teleport_restrictions row ({} columns): {}", fields.length, line);
				continue;
			}

			String name = fields[0].trim();
			if (name.isEmpty())
			{
				log.warn("Skipping teleport_restrictions row with empty family name");
				continue;
			}

			try
			{
				int displayItemId = Integer.parseInt(fields[1].trim());
				Set<Integer> memberItemIds = parseIdSet(fields[2]);
				Map<Integer, String> memberLabels =
					fields.length > 3 ? parseMemberLabels(fields[3]) : Collections.emptyMap();
				families.add(new Family(name, displayItemId,
					Collections.unmodifiableSet(memberItemIds),
					Collections.unmodifiableMap(memberLabels)));
			}
			catch (NumberFormatException e)
			{
				log.warn("Skipping malformed teleport_restrictions row: {}", line);
			}
		}

		return Collections.unmodifiableList(families);
	}

	private static Set<Integer> parseIdSet(String column)
	{
		Set<Integer> ids = new LinkedHashSet<>();
		for (String token : column.split(","))
		{
			String trimmed = token.trim();
			if (!trimmed.isEmpty())
			{
				ids.add(Integer.parseInt(trimmed));
			}
		}
		return ids;
	}

	private static Map<Integer, String> parseMemberLabels(String column)
	{
		Map<Integer, String> labels = new LinkedHashMap<>();
		for (String entry : column.split(","))
		{
			String trimmed = entry.trim();
			if (trimmed.isEmpty())
			{
				continue;
			}

			int eq = trimmed.indexOf('=');
			if (eq < 0)
			{
				log.warn("Skipping malformed memberLabels entry: {}", trimmed);
				continue;
			}

			try
			{
				labels.put(Integer.parseInt(trimmed.substring(0, eq)), trimmed.substring(eq + 1));
			}
			catch (NumberFormatException e)
			{
				log.warn("Skipping malformed memberLabels entry: {}", trimmed);
			}
		}
		return labels;
	}

	/**
	 * Parses the {@code blockedTeleportItems} CSV into a blocked-id set and a
	 * per-item threshold map. {@code id} records add to {@code blockedOut};
	 * {@code id:N} records merge into {@code thresholdOut} keeping the max N
	 * per id. Malformed entries are skipped with a warning; this method never
	 * throws on user-authored input.
	 */
	public static void parseBlocked(String csv, Set<Integer> blockedOut, Map<Integer, Integer> thresholdOut)
	{
		if (csv == null || csv.isBlank())
		{
			return;
		}

		for (String rawEntry : csv.split(","))
		{
			String entry = rawEntry.trim();
			if (entry.isEmpty())
			{
				continue;
			}

			int colon = entry.indexOf(':');
			try
			{
				if (colon < 0)
				{
					blockedOut.add(Integer.parseInt(entry));
				}
				else
				{
					int id = Integer.parseInt(entry.substring(0, colon).trim());
					int threshold = Integer.parseInt(entry.substring(colon + 1).trim());
					thresholdOut.merge(id, threshold, Math::max);
				}
			}
			catch (NumberFormatException e)
			{
				log.warn("Skipping malformed blockedTeleportItems entry: {}", entry);
			}
		}
	}

	/**
	 * Serializes a blocked-id set and threshold map back to the CSV contract:
	 * sorted blocked ids first, then sorted {@code id:N} threshold records.
	 * Empty (or null) inputs produce {@code ""}.
	 */
	public static String toCsv(Set<Integer> blocked, Map<Integer, Integer> thresholds)
	{
		StringBuilder sb = new StringBuilder();

		if (blocked != null)
		{
			List<Integer> ids = new ArrayList<>(blocked);
			Collections.sort(ids);
			for (int id : ids)
			{
				if (sb.length() > 0)
				{
					sb.append(',');
				}
				sb.append(id);
			}
		}

		if (thresholds != null)
		{
			List<Integer> ids = new ArrayList<>(thresholds.keySet());
			Collections.sort(ids);
			for (int id : ids)
			{
				if (sb.length() > 0)
				{
					sb.append(',');
				}
				sb.append(id).append(':').append(thresholds.get(id));
			}
		}

		return sb.toString();
	}
}
